In [19]:
import PIL
from PIL import Image
import torch
img = Image.open('Mask_Data/test/fully_covered/avgkcbjl.jpg')

In [20]:
img.mode

'L'

In [12]:
import numpy as np
import pandas as pd
import torch, torchvision
import torch.nn.functional as F
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils
from tqdm import tqdm

class ConvolutionBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(ConvolutionBlock, self).__init__()

        self.convs = nn.Sequential(
            nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=3, padding=0, stride=1),
            nn.BatchNorm2d(out_channels),
            nn.MaxPool2d(2),
            nn.ReLU()
        )

    def forward(self, X):
        return self.convs(X)

class Classifier(nn.Module):
    def __init__(self, in_channels,  num_classes) -> None:
        super(Classifier, self).__init__()

        conv1 = ConvolutionBlock(in_channels= in_channels, out_channels=8)
        conv2 = ConvolutionBlock(in_channels= 8, out_channels= 16)
        conv3 = ConvolutionBlock(in_channels= 16, out_channels=32)

        self.layers = nn.Sequential(conv1, conv2, conv3)

        self.fc = nn.Sequential(
            nn.Linear(in_features= 36864, out_features= 40),
            nn.ReLU(),
            nn.Linear(in_features=40, out_features=20),
            nn.ReLU(),
            nn.Linear(in_features=20, out_features=num_classes)
        )

    def forward(self, X):
        X = self.layers(X)
        X = torch.flatten(X)
        X = self.fc(X)
        X = F.log_softmax(X, dim=1)

        return X

In [17]:
random = torch.rand(32,3,64,64)
trial_ = Classifier(3, 4)
output = trial_(random)
output

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [7]:
a = torch.tensor([0.2083, 0.2225, 0.3034, 0.2658], requires_grad=True)
b = torch.tensor([1,1,0,1])
a

tensor([0.2083, 0.2225, 0.3034, 0.2658], requires_grad=True)

In [5]:
criterion = nn.CrossEntropyLoss()
criterion(a.float(),b.float())

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [8]:
a.view(-1)

tensor([0.2083, 0.2225, 0.3034, 0.2658], grad_fn=<ViewBackward0>)

In [10]:
loss = nn.CrossEntropyLoss()
input_ = torch.autograd.Variable(torch.randn(3, 5), requires_grad=True)
print(input)
target = torch.autograd.Variable(torch.LongTensor(3).random_(5))
output = loss(input_, target)
output.backward()

<bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x000001DF84543160>>


In [11]:
input_

tensor([[ 0.5195,  1.9821,  1.6755, -0.5837, -0.4413],
        [ 0.5167,  0.5308, -0.2967,  1.6571,  0.2556],
        [-0.3996, -0.4585, -0.0696, -1.4412, -1.2125]], requires_grad=True)

In [19]:
 torch.Tensor([1, 2]).to(torch.long)

tensor([1, 2])

In [20]:
yhat = torch.Tensor([[0.5, 1.5, 0.1], [2.2, 1.3, 1.7]])
print(yhat)
# tensor([[0.5000, 1.5000, 0.1000],
#         [2.2000, 1.3000, 1.7000]])

y = torch.Tensor([1, 2]).to(torch.long)
print(y)
# tensor([1, 2])

loss = torch.nn.CrossEntropyLoss()
cel = loss(input=yhat, target=y)
print(cel)
# tensor(0.8393)

tensor([[0.5000, 1.5000, 0.1000],
        [2.2000, 1.3000, 1.7000]])
tensor([1, 2])
tensor(0.8393)
